- hosts: localhost
  tasks:

    - name: Pull image
      shell: docker pull abhashti/calculator:latest

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Stop old container
      shell: docker stop Calculator
      ignore_errors: yes

    - name: Remove old container
      shell: docker rm Calculator
      ignore_errors: yes

    - name: Running container
      shell: docker run -it -d --name Calculator -p 8081:8080 abhashti/calculator:latest