- hosts: localhost
  tasks:

    - name: Pull image
      shell: docker pull abhashti/calculator:latest

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Stop and remove existing container on port 8081
      shell: |
        docker stop $(docker ps -q --filter "publish=8081") || true
        docker rm $(docker ps -aq --filter "publish=8081") || true
      ignore_errors: yes

    - name: Stop and remove container by name Calculator
      shell: |
        docker stop Calculator || true
        docker rm Calculator || true
      ignore_errors: yes

    - name: Running container
      shell: docker run -it -d --name Calculator -p 8081:8080 abhashti/calculator:latest